# Generated by Django 5.0.1 on 2024-03-09 05:54

import api.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, null=True)),
                ('url', models.CharField(max_length=1000, null=True)),
                ('comments', models.CharField(max_length=1000, null=True)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('retweets', models.IntegerField(default=0, null=True)),
                ('comment_date', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HashTagStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('history', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='InstagramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.CharField(max_length=100, null=True)),
                ('followers', models.CharField(max_length=20, null=True)),
                ('followings', models.CharField(max_length=20, null=True)),
                ('posts', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubScription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subscription_amount', models.CharField(max_length=100, null=True)),
                ('subscription_date', models.CharField(max_length=100, null=True)),
                ('subscription_expires_date', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.CharField(max_length=100, null=True)),
                ('followers', models.CharField(max_length=20, null=True)),
                ('followings', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.CharField(max_length=100, null=True)),
                ('views_count', models.IntegerField(default=0, null=True)),
                ('subscription_count', models.IntegerField(default=0, null=True)),
                ('video_count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, max_length=100, null=True)),
                ('hashtag_stats', models.ManyToManyField(related_name='hashtags', to='api.hashtagstats')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.ManyToManyField(related_name='instagram_profile', to='api.instagramprofile')),
            ],
        ),
        migrations.AddField(
            model_name='hashtagstats',
            name='instagram_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_stats', to='api.instagramstats'),
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=255)),
                ('hashtag_stats', models.ManyToManyField(related_name='hashtag_stat', to='api.hashtagstats')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('report_data', models.ManyToManyField(related_name='analysis_reports', to='api.reportdata')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('comments', models.ManyToManyField(related_name='twitter_comments', to='api.comment')),
                ('current_status', models.ManyToManyField(related_name='twitter_profile', to='api.twitterprofile')),
            ],
        ),
        migrations.AddField(
            model_name='hashtagstats',
            name='twitter_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_stats', to='api.twitterstats'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to=api.models.generate_filename)),
                ('subscription_status', models.ManyToManyField(related_name='subscription_status', to='api.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('current_status', models.ManyToManyField(related_name='youtube_profile', to='api.youtubeprofile')),
            ],
        ),
        migrations.AddField(
            model_name='hashtagstats',
            name='youtube_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_stats', to='api.youtubestats'),
        ),
    ]
