# Generated by Django 5.0.1 on 2024-01-18 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('retweets', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.CharField(max_length=20)),
                ('followings', models.CharField(max_length=20)),
                ('posts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('views_count', models.IntegerField(default=0)),
                ('subscription_count', models.IntegerField(default=0)),
                ('video_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.CharField(max_length=20)),
                ('followings', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('comment_date', models.DateField()),
                ('comments', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_comments', to='api.comment')),
            ],
        ),
        migrations.CreateModel(
            name='HashTagStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hashtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('instagram_stats', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_stats', to='api.instagramstats')),
                ('twitter_stats', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_stats', to='api.twitterstats')),
                ('youtube_stats', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_stats', to='api.youtubestats')),
            ],
        ),
    ]
