# Generated by Django 5.0.1 on 2024-01-19 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='retweets',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='instagramstats',
            name='followers',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='instagramstats',
            name='followings',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='instagramstats',
            name='posts',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='twitterstats',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='twitter_comments', to='api.comment'),
        ),
        migrations.AlterField(
            model_name='twitterstats',
            name='followers',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='twitterstats',
            name='followings',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='twitterstats',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='subscription_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='video_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='views_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
