# Generated by Django 5.0.1 on 2024-01-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_hashtag_instagramstats_youtubestats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
