# Generated by Django 5.0.1 on 2024-01-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_comment_comment_date_alter_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterstats',
            name='comments',
            field=models.ManyToManyField(related_name='twitter_comments', to='api.comment'),
        ),
    ]
