# Generated by Django 5.0.1 on 2024-01-19 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_twitterstats_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterstats',
            name='joining_date',
            field=models.DateField(null=True, verbose_name=django.utils.timezone.now),
        ),
    ]
