# Generated by Django 5.0.1 on 2024-01-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_hashtagstats_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
