# Generated by Django 5.0.1 on 2024-01-18 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_hashtag_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_stats',
            field=models.ManyToManyField(related_name='hashtags', to='api.hashtagstats'),
        ),
        migrations.AlterField(
            model_name='hashtagstats',
            name='instagram_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_stats', to='api.instagramstats'),
        ),
        migrations.AlterField(
            model_name='hashtagstats',
            name='twitter_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_stats', to='api.twitterstats'),
        ),
        migrations.AlterField(
            model_name='hashtagstats',
            name='youtube_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_stats', to='api.youtubestats'),
        ),
    ]
