# Generated by Django 5.0.1 on 2024-01-19 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_twitterstats_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterstats',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
