# Generated by Django 5.0.1 on 2024-01-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_twitterstats_joining_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
