# Generated by Django 5.0.1 on 2024-01-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_hashtag_hashtag_stats_hashtag_hashtag_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='hashtag_stats',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_stats',
            field=models.ManyToManyField(related_name='hashtags', to='api.hashtagstats'),
        ),
    ]
