# Generated by Django 5.0.1 on 2024-01-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_hashtag_hashtag_stats_hashtag_hashtag_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterstats',
            name='comment_date',
        ),
        migrations.RemoveField(
            model_name='twitterstats',
            name='comments',
        ),
        migrations.AddField(
            model_name='twitterstats',
            name='comments',
            field=models.ManyToManyField(related_name='twitter_comments', to='api.comment'),
        ),
    ]
