# Generated by Django 5.0.1 on 2024-01-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_twitterstats_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(default=None),
        ),
    ]
