# Generated by Django 5.0.1 on 2024-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
