# Generated by Django 5.0.1 on 2024-02-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_hashtagstats_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
