# Generated by Django 5.0.1 on 2024-02-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
