# Generated by Django 5.0.1 on 2024-02-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_hashtagincludesearch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterstats',
            name='hashtagIncludeSearch',
        ),
        migrations.DeleteModel(
            name='HashtagIncludeSearch',
        ),
    ]
