# Generated by Django 5.0.1 on 2024-02-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_user_subscription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
