# Generated by Django 5.0.1 on 2024-02-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_user_subscription_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.CharField(max_length=100, null=True)),
                ('followers', models.CharField(max_length=20, null=True)),
                ('followings', models.CharField(max_length=20, null=True)),
                ('posts', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.CharField(max_length=100, null=True)),
                ('followers', models.CharField(max_length=20, null=True)),
                ('followings', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.CharField(max_length=100, null=True)),
                ('views_count', models.IntegerField(default=0, null=True)),
                ('subscription_count', models.IntegerField(default=0, null=True)),
                ('video_count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instagramstats',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='instagramstats',
            name='followings',
        ),
        migrations.RemoveField(
            model_name='instagramstats',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='twitterstats',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='twitterstats',
            name='followings',
        ),
        migrations.RemoveField(
            model_name='youtubestats',
            name='subscription_count',
        ),
        migrations.RemoveField(
            model_name='youtubestats',
            name='video_count',
        ),
        migrations.RemoveField(
            model_name='youtubestats',
            name='views_count',
        ),
        migrations.AddField(
            model_name='instagramstats',
            name='current_status',
            field=models.ManyToManyField(related_name='instagram_profile', to='api.instagramprofile'),
        ),
        migrations.AddField(
            model_name='twitterstats',
            name='current_status',
            field=models.ManyToManyField(related_name='twitter_profile', to='api.twitterprofile'),
        ),
        migrations.AddField(
            model_name='youtubestats',
            name='current_status',
            field=models.ManyToManyField(related_name='youtube_profile', to='api.youtubeprofile'),
        ),
    ]
