# Generated by Django 5.0.1 on 2024-02-26 08:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_instagramprofile_twitterprofile_youtubeprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubScription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subscription_amount', models.CharField(max_length=100, null=True)),
                ('subscription_date', models.CharField(max_length=100, null=True)),
                ('subscription_expires_date', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_amount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_expires_date',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.ManyToManyField(related_name='hashtags', to='api.subscription'),
        ),
    ]
