# Generated by Django 5.0.1 on 2024-03-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_hashtagstats_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
